# Based on https://github.com/buildkite/bazel-example
steps:
  - label: ":bazel: Build"
    commands:
      - bazel build //...
  - label: ":bazel: Test"
    commands:
      - bazel test //...
      - echo success

